"""Host-neutral Mem0-flat prompt and completion contracts."""

from .prompts import (
    FACT_EXTRACTION_PROMPT,
    INTERNAL_OPERATION_PROMPT,
    MEMBASE_COMMIT,
    MEMBASE_LICENSE,
    MEMBASE_PROMPT_PATH,
    MEMBASE_SOURCE_DIGEST,
    PROMPT_CONTRACT_SCHEMA_VERSION,
    SEMANTIC_RETRIEVAL_SCORER_PROMPT,
    CompletionResult,
    CompletionClient,
    FakeCompletionClient,
    PromptArtifact,
    PromptSourceProvenance,
    PromptTemplate,
    POLICY_FACT_EXTRACTION_PROMPT,
    POLICY_INTERNAL_OPERATION_PROMPT,
    RenderedPrompt,
    build_prompt_catalog,
    build_policy_prompt_catalog,
)
from .policy import (
    MEM0_FLAT_POLICY_SCHEMA_VERSION,
    ExtractedSemanticFact,
    FlatRetrievalConfig,
    FlatSemanticCandidateReader,
    Mem0FlatSemanticPolicy,
    RelatedMemoryView,
    build_validation_candidate,
)

__all__ = [
    "CompletionResult",
    "CompletionClient",
    "FACT_EXTRACTION_PROMPT",
    "FakeCompletionClient",
    "INTERNAL_OPERATION_PROMPT",
    "MEMBASE_COMMIT",
    "MEMBASE_LICENSE",
    "MEMBASE_PROMPT_PATH",
    "MEMBASE_SOURCE_DIGEST",
    "PROMPT_CONTRACT_SCHEMA_VERSION",
    "PromptArtifact",
    "PromptSourceProvenance",
    "PromptTemplate",
    "POLICY_FACT_EXTRACTION_PROMPT",
    "POLICY_INTERNAL_OPERATION_PROMPT",
    "RenderedPrompt",
    "SEMANTIC_RETRIEVAL_SCORER_PROMPT",
    "build_prompt_catalog",
    "build_policy_prompt_catalog",
    "MEM0_FLAT_POLICY_SCHEMA_VERSION",
    "ExtractedSemanticFact",
    "FlatRetrievalConfig",
    "FlatSemanticCandidateReader",
    "Mem0FlatSemanticPolicy",
    "RelatedMemoryView",
    "build_validation_candidate",
]
