"""Host-neutral Mem0-flat prompt and completion contracts."""

from .prompts import (
    FACT_EXTRACTION_PROMPT,
    INTERNAL_OPERATION_PROMPT,
    MEMBASE_COMMIT,
    MEMBASE_LICENSE,
    MEMBASE_PROMPT_PATH,
    MEMBASE_SOURCE_DIGEST,
    PROMPT_CONTRACT_SCHEMA_VERSION,
    SEMANTIC_RETRIEVAL_SCORER_PROMPT,
    CompletionResult,
    CompletionClient,
    FakeCompletionClient,
    PromptArtifact,
    PromptSourceProvenance,
    PromptTemplate,
    POLICY_FACT_EXTRACTION_PROMPT,
    POLICY_FACT_EXTRACTION_FROZEN_WRAPPER,
    POLICY_FACT_EXTRACTION_ROOT_BODY,
    POLICY_INTERNAL_OPERATION_PROMPT,
    RenderedPrompt,
    build_prompt_catalog,
    build_policy_prompt_catalog,
    compile_policy_fact_extraction_template,
)
from .prompt_adapter import (
    MEM0_FLAT_EXTRACTION_SLOT,
    MEM0_FLAT_EXTRACTION_SLOT_ID,
    MEM0_FLAT_PROMPT_ADAPTER_ID,
    Mem0FlatPromptAdapter,
)
from .policy import (
    MEM0_FLAT_POLICY_SCHEMA_VERSION,
    ExtractedSemanticFact,
    FlatRetrievalConfig,
    FlatSemanticCandidateReader,
    Mem0FlatSemanticPolicy,
    RelatedMemoryView,
    build_validation_candidate,
)
from .utility_gate import (
    FROZEN_MEM0_UTILITY_GATE_VERSION,
    FrozenMem0UtilityConfig,
    FrozenMem0UtilityGate,
)

__all__ = [
    "CompletionResult",
    "CompletionClient",
    "FACT_EXTRACTION_PROMPT",
    "FakeCompletionClient",
    "INTERNAL_OPERATION_PROMPT",
    "MEMBASE_COMMIT",
    "MEMBASE_LICENSE",
    "MEMBASE_PROMPT_PATH",
    "MEMBASE_SOURCE_DIGEST",
    "PROMPT_CONTRACT_SCHEMA_VERSION",
    "PromptArtifact",
    "PromptSourceProvenance",
    "PromptTemplate",
    "POLICY_FACT_EXTRACTION_PROMPT",
    "POLICY_FACT_EXTRACTION_FROZEN_WRAPPER",
    "POLICY_FACT_EXTRACTION_ROOT_BODY",
    "POLICY_INTERNAL_OPERATION_PROMPT",
    "RenderedPrompt",
    "SEMANTIC_RETRIEVAL_SCORER_PROMPT",
    "build_prompt_catalog",
    "build_policy_prompt_catalog",
    "compile_policy_fact_extraction_template",
    "MEM0_FLAT_EXTRACTION_SLOT",
    "MEM0_FLAT_EXTRACTION_SLOT_ID",
    "MEM0_FLAT_PROMPT_ADAPTER_ID",
    "Mem0FlatPromptAdapter",
    "MEM0_FLAT_POLICY_SCHEMA_VERSION",
    "ExtractedSemanticFact",
    "FlatRetrievalConfig",
    "FlatSemanticCandidateReader",
    "Mem0FlatSemanticPolicy",
    "RelatedMemoryView",
    "build_validation_candidate",
    "FROZEN_MEM0_UTILITY_GATE_VERSION",
    "FrozenMem0UtilityConfig",
    "FrozenMem0UtilityGate",
]
